using MudBlazor;

namespace Checkbus.UI;

/// <summary>
/// Design-system theme generated by Material Theme Builder from seed color
/// #390D74 (see Data/material-theme.json — "light" and "dark" schemes),
/// replacing the earlier logo-derived navy/orange palette. Dark mode is the
/// active default per product-owner request.
/// </summary>
public static class CheckbusTheme
{
    public static MudTheme Default { get; } = new()
    {
        PaletteLight = new PaletteLight
        {
            Primary = "#69548D",
            PrimaryContrastText = "#FFFFFF",
            Secondary = "#635B70",
            SecondaryContrastText = "#FFFFFF",
            Tertiary = "#7F525C",
            TertiaryContrastText = "#FFFFFF",
            AppbarBackground = "#69548D",
            Background = "#FEF7FF",
            Surface = "#FFFFFF",
            TextPrimary = "#1D1A20",
            TextSecondary = "#49454E",
            Success = "#2E7D32",
            Error = "#BA1A1A",
            ErrorContrastText = "#FFFFFF",
            Warning = "#ED6C02",
            Info = "#0288D1",
        },
        PaletteDark = new PaletteDark
        {
            Primary = "#D4BBFC",
            PrimaryContrastText = "#39255B",
            Secondary = "#CDC2DB",
            SecondaryContrastText = "#342D40",
            Tertiary = "#F1B7C4",
            TertiaryContrastText = "#4A252F",
            AppbarBackground = "#2C292F",
            Background = "#151218",
            Surface = "#211F24",
            TextPrimary = "#E7E0E8",
            TextSecondary = "#CBC4CF",
            Success = "#8BD186",
            Error = "#FFB4AB",
            ErrorContrastText = "#690005",
            Warning = "#FFB77C",
            Info = "#89CFF7",
        },
        LayoutProperties = new LayoutProperties
        {
            DefaultBorderRadius = "12px",
        },
        Typography = new Typography
        {
            Default = new DefaultTypography
            {
                FontFamily = ["Inter", "Segoe UI", "sans-serif"],
            },
        },
    };
}
