// <auto-generated />
using System;
using Checkbus.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Checkbus.DAL.Migrations
{
    [DbContext(typeof(CheckbusDbContext))]
    [Migration("20260903193637_AddFleetEntities")]
    partial class AddFleetEntities
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Checkbus.BEL.Auth.Permission", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Key")
                        .IsUnique();

                    b.ToTable("Permissions", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Key = "reports.view"
                        },
                        new
                        {
                            Id = 2,
                            Key = "reports.manage"
                        },
                        new
                        {
                            Id = 3,
                            Key = "roles.manage"
                        },
                        new
                        {
                            Id = 4,
                            Key = "users.manage"
                        },
                        new
                        {
                            Id = 5,
                            Key = "routes.manage"
                        },
                        new
                        {
                            Id = 6,
                            Key = "trips.manage"
                        },
                        new
                        {
                            Id = 7,
                            Key = "trips.drive"
                        },
                        new
                        {
                            Id = 8,
                            Key = "vehicles.manage"
                        },
                        new
                        {
                            Id = 9,
                            Key = "incidents.manage"
                        },
                        new
                        {
                            Id = 10,
                            Key = "incidents.validate"
                        });
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int?>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_Name_Global")
                        .HasFilter("\"OrganizationId\" IS NULL");

                    b.HasIndex("OrganizationId", "Name")
                        .IsUnique()
                        .HasDatabaseName("IX_Roles_OrganizationId_Name_Custom")
                        .HasFilter("\"OrganizationId\" IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Planificador"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Mantenimiento"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Validador"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Chofer"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Administrador"
                        });
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.RolePermission", b =>
                {
                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.Property<int>("PermissionId")
                        .HasColumnType("integer");

                    b.HasKey("RoleId", "PermissionId");

                    b.HasIndex("PermissionId");

                    b.ToTable("RolePermissions", (string)null);

                    b.HasData(
                        new
                        {
                            RoleId = 5,
                            PermissionId = 4
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 3
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 2
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 5,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 5
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 6
                        },
                        new
                        {
                            RoleId = 1,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 8
                        },
                        new
                        {
                            RoleId = 2,
                            PermissionId = 9
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 10
                        },
                        new
                        {
                            RoleId = 3,
                            PermissionId = 1
                        },
                        new
                        {
                            RoleId = 4,
                            PermissionId = 7
                        });
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RoleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("RoleId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Attachment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("DriverId")
                        .HasColumnType("integer");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<long>("SizeBytes")
                        .HasColumnType("bigint");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int?>("VehicleDocumentationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DriverId");

                    b.HasIndex("VehicleDocumentationId");

                    b.ToTable("Attachments", null, t =>
                        {
                            t.HasCheckConstraint("CK_Attachments_ExactlyOneOwner", "(\"VehicleDocumentationId\" IS NOT NULL AND \"DriverId\" IS NULL) OR (\"VehicleDocumentationId\" IS NULL AND \"DriverId\" IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.ComponentDiagnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Component")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VehicleDiagnosticId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleDiagnosticId");

                    b.ToTable("ComponentDiagnostics", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Driver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Dni")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Dni")
                        .IsUnique();

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.License", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("DriverId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamptz");

                    b.HasKey("Id");

                    b.HasIndex("DriverId")
                        .IsUnique();

                    b.ToTable("Licenses", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.MaintenanceRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AffectedComponents")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("timestamptz");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("MaintenanceRecords", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Vehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Capacity")
                        .HasColumnType("integer");

                    b.Property<string>("CurrentDiagnosticState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("integer");

                    b.Property<string>("Plate")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("OrganizationId", "Plate")
                        .IsUnique();

                    b.ToTable("Vehicles", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDiagnostic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Mileage")
                        .HasColumnType("integer");

                    b.Property<string>("OverallState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("RecordedAt")
                        .HasColumnType("timestamptz");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId");

                    b.ToTable("VehicleDiagnostics", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDocumentation", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("DocumentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("VehicleId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("VehicleId", "DocumentNumber")
                        .IsUnique();

                    b.ToTable("VehicleDocumentations", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Organization.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Cuit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("Cuit")
                        .IsUnique();

                    b.ToTable("Organizations", (string)null);
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.RolePermission", b =>
                {
                    b.HasOne("Checkbus.BEL.Auth.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Checkbus.BEL.Auth.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.User", b =>
                {
                    b.HasOne("Checkbus.BEL.Auth.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Attachment", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.Driver", "Driver")
                        .WithMany("Attachments")
                        .HasForeignKey("DriverId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Checkbus.BEL.Fleet.VehicleDocumentation", "VehicleDocumentation")
                        .WithMany("Attachments")
                        .HasForeignKey("VehicleDocumentationId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Driver");

                    b.Navigation("VehicleDocumentation");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.ComponentDiagnostic", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.VehicleDiagnostic", "VehicleDiagnostic")
                        .WithMany("Components")
                        .HasForeignKey("VehicleDiagnosticId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VehicleDiagnostic");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.License", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.Driver", "Driver")
                        .WithOne("License")
                        .HasForeignKey("Checkbus.BEL.Fleet.License", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Driver");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.MaintenanceRecord", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.Vehicle", "Vehicle")
                        .WithMany("MaintenanceRecords")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDiagnostic", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.Vehicle", "Vehicle")
                        .WithMany("Diagnostics")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDocumentation", b =>
                {
                    b.HasOne("Checkbus.BEL.Fleet.Vehicle", "Vehicle")
                        .WithMany("Documentations")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("Checkbus.BEL.Auth.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Driver", b =>
                {
                    b.Navigation("Attachments");

                    b.Navigation("License");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.Vehicle", b =>
                {
                    b.Navigation("Diagnostics");

                    b.Navigation("Documentations");

                    b.Navigation("MaintenanceRecords");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDiagnostic", b =>
                {
                    b.Navigation("Components");
                });

            modelBuilder.Entity("Checkbus.BEL.Fleet.VehicleDocumentation", b =>
                {
                    b.Navigation("Attachments");
                });
#pragma warning restore 612, 618
        }
    }
}
