<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>641b2aa9-595e-4e52-b421-1a534c4f4ef7</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="MudBlazor" Version="9.10.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Checkbus.ServiceDefaults\Checkbus.ServiceDefaults.csproj" />
  </ItemGroup>

</Project>
