<Project Sdk="Aspire.AppHost.Sdk/13.5.2">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>33f35b95-63ec-4243-8507-c2664e977e45</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Checkbus.ApiService\Checkbus.ApiService.csproj" />
    <ProjectReference Include="..\Checkbus.Web\Checkbus.Web.csproj" />
  </ItemGroup>

</Project>
