namespace Checkbus.ApiService.Application.Interfaces.Storage
{
    /// <summary>Storage-agnostic file access. Keys are opaque, relative, backend-defined
    /// identifiers generated by the application — never raw client filenames, never paths.</summary>
    public interface IFileStorageService
    {
        Task<string> SaveAsync(string key, Stream content, string contentType, CancellationToken cancellationToken);
        Task<Stream?> OpenReadAsync(string key, CancellationToken cancellationToken);
        Task<bool> ExistsAsync(string key, CancellationToken cancellationToken);
        Task DeleteAsync(string key, CancellationToken cancellationToken);
    }
}
